### ISSUE TITLE
[BUG] Webview does not open again, once closed

### ISSUE THREAD

**Issue by ghost** [TheShark34/OpenAuth#42]
**Describe the bug**
Whenever I run `MicrosoftAuthResult microsoftAuthResult = microsoftAuthenticator.loginWithWebview();` for the first time, the webview opens. But when I close the webview window and rerun that code, it does not open again (unless I restart the Java process entirely)

**To Reproduce**
1. Run 'MicrosoftAuthResult microsoftAuthResult = microsoftAuthenticator.loginWithWebview();'
2. Close the webview window once it appears
3. Rerun the code 'MicrosoftAuthResult microsoftAuthResult = microsoftAuthenticator.loginWithWebview();'
4. You can see how it doesn't appear now

**Expected behavior**
The webview appears as expected.

**Desktop**
 - OS: Windows 11
 - Oracle Java 20.0.2
 - OpenAuth Version: 1.1.6

**Additional context**
The line also hangs the java process or thread

**Comment by x3liinaa** [comment]
What is the fix for this now?
